version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: auth-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - auth-network

  # Backend API service
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.service
    container_name: auth-service-api
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/auth-service
      - JWT_SECRET=your_jwt_secret_key_here_please_change_in_production
      - JWT_EXPIRES_IN=1d
      - REFRESH_TOKEN_SECRET=your_refresh_token_secret_key_here_please_change_in_production
      - REFRESH_TOKEN_EXPIRES_IN=7d
      - ALLOWED_ORIGINS=http://localhost:3000
    networks:
      - auth-network

  # Frontend UI service
  auth-ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: auth-ui
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
    networks:
      - auth-network

# Volumes
volumes:
  mongodb_data:
    driver: local

# Networks
networks:
  auth-network:
    driver: bridge 