version: '3.8'

services:
  # MongoDB service
  auth-mongodb:
    image: mongo:latest
    container_name: auth-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=auth-service
    volumes:
      - mongodb_data:/data/db
      - ./db/mongo/seeds:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--quiet"]
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 10s

  # Backend API service
  auth-service-api:
    build:
      context: .
      dockerfile: Dockerfile.service
    container_name: auth-service-api
    ports:
      - "5001:5000"
    depends_on:
      auth-mongodb:
        condition: service_healthy
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://auth-mongodb:27017/auth-service
      - JWT_SECRET=your_jwt_secret_key_here_please_change_in_production
      - JWT_EXPIRES_IN=1d
      - REFRESH_TOKEN_SECRET=your_refresh_token_secret_key_here_please_change_in_production
      - REFRESH_TOKEN_EXPIRES_IN=7d
      - ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./src/service:/app

  # Frontend UI service
  auth-ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: auth-ui
    ports:
      - "3000:3000"
    volumes:
      - ./src/ui:/app/src
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

# Volumes
volumes:
  mongodb_data:
    driver: local

# Networks
networks:
  auth-network:
    driver: bridge 