version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: auth-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./db/mongo/seeds:/docker-entrypoint-initdb.d
    networks:
      - auth-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--quiet"]
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 10s

  # Backend API service
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.service
    container_name: auth-service-api
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_EXPIRES_IN=${REFRESH_TOKEN_EXPIRES_IN}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
    volumes:
      - ./src/service:/app
    networks:
      - auth-network

  # Frontend UI service
  auth-ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: auth-ui
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
    volumes:
      - ./src/ui:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
    networks:
      - auth-network

# Volumes
volumes:
  mongodb_data:
    driver: local

# Networks
networks:
  auth-network:
    driver: bridge 