apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: us-central1-docker.pkg.dev/template-1743820446385/docker-registry/auth-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"
        - name: HOST
          value: "0.0.0.0"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: mongodb-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: jwt-secret
        - name: RECAPTCHA_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: recaptcha-secret-key
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: auth-service 