apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
type: Opaque
stringData:
  mongodb-uri: "mongodb://your-mongodb-uri"  # Replace with your MongoDB URI
  jwt-secret: "your-jwt-secret"              # Replace with your JWT secret 